FROM eclipse-mosquitto
LABEL image-de-base="https://hub.docker.com/_/eclipse-mosquitto"
MAINTAINER My909

RUN echo mosquitto

## Add the wait script to the image
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
# RUN chmod +x /wait
# CMD ["/wait"]